name: Bug Report
description: File a bug report
title: "Bug: "
labels: ["bug]
body:
  - type: input
    id: where
    attributes:
      label: Affected Files
      description: Which files are affected?
      placeholder: ex. Robot.java
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you expect to happen?
      placeholder: Tell us what you see!
      value: "X happened when Y was supposed to happen."
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What does this affect?
      options:
        - Vision
        - Drive
        - Control
        - Marker Detection
        - Teleop
        - Auto
